### ISSUE TITLE
pyDriveWire not saving config

### ISSUE THREAD

**Issue by drencorxeen** [n6il/pyDriveWire#6]
When trying to save config with the follow it gives errors:
```
pyDriveWire(0)>  dw config save
ERROR:: [Errno 2] No such file or directory: '~/.pydrivewirerc'
Traceback (most recent call last):
  File "/home/dladd/src/pyDriveWire/dwcommand.py", line 860, in doRepl
    r = self.parser.parse(wdata, True)
  File "/home/dladd/src/pyDriveWire/dwcommand.py", line 811, in parse
    res = v.call(callData)
  File "/home/dladd/src/pyDriveWire/dwcommand.py", line 82, in call
    return self.fn(*args)
  File "/home/dladd/src/pyDriveWire/dwcommand.py", line 758, in doConfigSave
    with open(outFile, 'w') as f:
IOError: [Errno 2] No such file or directory: '~/.pydrivewirerc'
pyDriveWire(0)>


```

**Comment by drencorxeen** [comment]
```
Also here is the directory listing so the .pydrivewirerc does exist in my home folder:

total 16
0 drwxr-xr-x 1 dave dave  512 May 10 00:02 .
0 drwxr-xr-x 1 root  root   512 May  5 22:00 ..
4 -rw------- 1 dave dave 1680 May  9 15:17 .bash_history
0 -rw-r--r-- 1 dave dave  220 May  5 22:00 .bash_logout
4 -rw-r--r-- 1 dave dave 3771 May  5 22:00 .bashrc
0 drwxr-xr-x 1 dave dave  512 May  5 22:00 .landscape
0 drwxrwxrwx 1 dave dave  512 May  6 23:02 .local
0 -rw-rw-rw- 1 dave dave    0 May  9 14:27 .motd_shown
4 -rw-r--r-- 1 dave dave  807 May  5 22:00 .profile
4 -rw-r--r-- 1 dave dave  862 May 10 00:02 .pydrivewirerc
0 -rw-rw-rw- 1 dave dave   13 May  6 23:01 .python_history
0 drwx------ 1 dave dave  512 May  6 23:02 .ssh
0 -rw-r--r-- 1 dave dave    0 May  5 22:00 .sudo_as_admin_successful
0 drwx------ 1 dave dave  512 May  7 21:14 bin
0 drwxrwxrwx 1 dave dave  512 May  9 23:38 coco
0 drwxrwxrwx 1 dave dave  512 May  6 23:06 src

```
